package rules
import com.microservices.shared.SensorReadingMapped

declare SensorReadingMapped
    @role(event)
end

declare window LastReadings
    SensorReadingMapped() over window:length(10) from entry-point "ReadingStream"
end

rule "rule2"
    no-loop true
    lock-on-active true
    salience 1
    when
        Number(intValue > 1) from accumulate(
                $r : SensorReadingMapped(content["value8"] == 7) from window LastReadings,
                count($r))
    then
        System.out.println("DEBIL");
end